version: '2'
services:
  test:
    build: .
    ports:
     - "8000:8000"
    volumes:
     - .:/code
    links:
     - postgres
    depends_on:
     - postgres
    environment:
     - DATABASE_URL=mysql://root@mysql:3306/test
  postgres:
    image: postgres:latest
    environment:
    - DATABASE_URL=mysql://root@localhost:3306/test

